name: Latest blog post workflow
on:
  schedule:
    # Runs every day at 13
    - cron: "* 13 * * *"
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in lucashanson posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://lucashanson.dk/rss.xml"
          template: '<li><a href="$url">$title</a></li>$newline'
          commit_message: "Update with latest blog post"
