on:
   workflow_dispatch:
   schedule:
      - cron: "0 15 * * *" # runs everyday at 3:00pm
jobs:
   update_readme:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
         - uses: actions/checkout@v2
         - name: Get Youtube Videos
           uses: pmqueiroz/readme-last-youtube-videos@main
           env:
              YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
           with:
              channel_id: "UCSf9uWEmXyOw4lfyPzpnYAA"
         - name: Configure Git
           run: |
             git config user.name "github-actions[bot]"
             git config user.email "github-actions[bot]@users.noreply.github.com"
             git pull --rebase origin main  # Pull and rebase to resolve conflicts
             git push origin main
         - name: Push changes
           uses: actions-js/push@master
           with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              
