name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every day at 13
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCSf9uWEmXyOw4lfyPzpnYAA
          output_type: html
          commit_message: "Update YouTube cards"
